name: Android CI (FootPrint Debug)

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Ako ih koristiš, dodaćemo ih kao Secrets u Settings → Secrets → Actions
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      JAVA_TOOL_OPTIONS: -Xmx2g
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Ensure Gradlew is executable
        run: chmod +x ./gradlew

      # rešava "SDK location not found" bez komitovanja local.properties
      - name: Create local.properties (sdk.dir)
        run: echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties

      # ubaci Secrets u ~/.gradle/gradle.properties da ih Gradle vidi kao project properties
      - name: Inject secrets into Gradle properties
        run: |
          mkdir -p ~/.gradle
          {
            echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}"
            echo "MAPBOX_PUBLIC_TOKEN=${MAPBOX_PUBLIC_TOKEN}"
            echo "MAPBOX_DOWNLOADS_TOKEN=${MAPBOX_DOWNLOADS_TOKEN}"
          } >> ~/.gradle/gradle.properties

      - name: Dependencies
        run: ./gradlew --stacktrace --info --warning-mode=all dependencies

      - name: Build Debug
        run: ./gradlew --stacktrace --info --warning-mode=all clean assembleDebug

      - name: Unit tests
        run: ./gradlew --stacktrace --info testDebugUnitTest

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: FootPrint-debug-apk
          path: app/build/outputs/apk/debug/*.apk
